### PR TITLE
new stretch/scale sliders

### PR DESCRIPTION
**Pull request by majkelx**

### CODE REVIEW

**Comment by majkelx** [comment]
On my computer new sliders panel looks like this:
Screenshot 2020-09-18 at 21 36 26
I will try to correct spacing somehow

**Comment by majkelx** [comment]
1. I have changed `QGridLayout` to `QFormLayout` on stretch panels: 'manual' and 'zscale'. Check if it looks ok, and if so change  other panels accordingly.
2. I have also adjusted (removed) additional margins from new new Slider widgets. I have made common base class `LabeledSlder` for both sliders. On some moment you can move similiar and identical methods of Slider classes up to this base class
3. `slider_min` `slider_max` `slider_step`  should be handled differently for `IntSlider`. When sliding there should be always integer values in the editbox etc... I have changed this, that slder min, max is the dame as control min, max, just step is adjusted to do not exceed 100 stop-points.
4. I do not understand why `QLocale.German`?
5. Labels width and/or numbers formatting (numer of decimals) has to be adjusted.

**Comment by mbrodniak** [comment]
I have changed QLocale to default system locale by using default constructor. I have also changed all QGridLayouts to QFormLayouts as you proposed.
Numbers of decimals have been adjusted to two decimal points.

**Comment by mbrodniak** [comment]
A height of dynamic scale widget has been adjusted. It should automatically resizes and looks better than before.

**Comment by majkelx** [comment]
I will check how it looks today. Have you checked on a Mac?

**Comment by mbrodniak** [comment]
Yes, I 've checked on a Mac and Windows and both look good.

**Pull request merged**
